// frontend/src/components/Header/Header.tsx
import type { JSXElement } from 'solid-js';
import GithubIcon from '~/icons/GithubIcon';
import './Header.scss';

export function Header(): JSXElement {
  return (
    <header class="Header">
      <h1 class="title">GRAPHENE</h1>
      <span class="subtitle">Create and share beautiful code snippets!</span>
      <a class="button" href="https://github.com/teknologi-umum/graphene">
        <GithubIcon /> See on Github
      </a>
    </header>
  );
}

// src/views/src/components/Header/header.tsx
import styles from './header.module.css';

export default function Header() {
  return (
    <header className={styles.header}>
      <h1 className={styles.header__title}>GRAPHENE</h1>
      <span className={styles.header__subtitle}>Create and share beautiful code snippets!</span>
    </header>
  );
}
